spring.application.name=staff-management
server.port=${SERVER_PORT:9090}

# SQLite config
spring.datasource.url=jdbc:sqlite:${spring.application.name}.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA
spring.jpa.database-platform=it.atrevisan.staffmanagement.config.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

#Vaadin
vaadin.launch-browser=true
vaadin.compatibilityMode=false
